name: LVM_GENERATE_UPDATE_EXE
on:
  workflow_dispatch:

jobs:
  GENERATE_UPDATE_EXE:
    runs-on: windows-latest
    env:
      SUBDIRECTORY: new_update
      PROGRAM_VERSION_FILENAME: version.py
      DFS_Path_Updater: \\d1\DfsLvm\Applications\Landesk\Applications\OneRetail\tmp\CMDB_Testing
      CUSTOM_PYTHON_VERSION: '310'
      VIRTUAL_ENV_DIR: venvupgrader310_master
      IT_GroovyConfigFile: config.groovy
      last_build_version: 336
      last_build_version_Program_Keyword: last_build_version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Display Python Path
        run: |
          python --version
          where python
          echo "Python is installed at: $(where python)"

      - name: Install venv and Python dependencies
        run: |
          Write-Host "Creating python virtual env in folder $env:VIRTUAL_ENV_DIR..."
          & $env:CUSTOM_PYTHON_PATH -m venv $env:VIRTUAL_ENV_DIR
          & "$env:VIRTUAL_ENV_EXE\python.exe" -m pip install --upgrade pip
          Write-Host "Installing python dependencies..."
          & "$env:VIRTUAL_ENV_EXE\python.exe" -m pip install -r ${{ github.workspace }}\$env:SUBDIRECTORY\requirements.txt

      - name: Increment version
        run: |
          $SCRIPT_DIRECTORY = "${{ github.workspace }}\$env:SUBDIRECTORY"
          $PROGRAM_VERSION_FILE = "$SCRIPT_DIRECTORY\$env:PROGRAM_VERSION_FILENAME"
          Write-Host "Reading version file $PROGRAM_VERSION_FILE"
          $lines = Get-Content $PROGRAM_VERSION_FILE
          $last_build_version = $env:last_build_version
          foreach ($line in $lines) {
            if ($line.Contains($env:last_build_version_Program_Keyword)) {
              $line = $line.Trim().Replace("'", "")
              if ($line.Contains($env:last_build_version_Program_Keyword + '=')) {
                $last_build_version = [int]$line.Split('=')[1]
              }
            }
          }
          $new_build_version = $last_build_version + 1
          Write-Host "Increment script version from $last_build_version to $new_build_version in $PROGRAM_VERSION_FILE"
          
          (Get-Content $PROGRAM_VERSION_FILE) | 
            ForEach-Object { $_ -replace "($env:last_build_version_Program_Keyword\s*=.*)($last_build_version)(.*)", "`$1$new_build_version`$3" } |
            Set-Content $PROGRAM_VERSION_FILE

      - name: Run unit tests
        run: |
          Write-Host "Running unit tests..."
          cd ${{ github.workspace }}\$env:SUBDIRECTORY
          .\run_testunit.bat $env:VIRTUAL_ENV_EXE\python.exe

      - name: Run SonarQube analysis
        run: |
          Write-Host "Running SonarQube analysis..."
          $scannerHome = "D:\Program\sonar-scanner-4.0"
          & "$scannerHome\bin\sonar-scanner.bat" -Dsonar.projectKey=onr-upgrader -Dsonar.projectName=onr-upgrader -Dsonar.projectVersion=$new_build_version -Dsonar.sources=${{ github.workspace }}\$env:SUBDIRECTORY -Dsonar.exclusions=venv/**,unit_test/**,htmlcov/**,test-report/**,update_fake.py,testing.py

      - name: Generate Executable
        run: |
          Write-Host "Generating executable..."
          & "$env:VIRTUAL_ENV_EXE\python.exe" --version
          & "$env:VIRTUAL_ENV_EXE\pyinstaller" --onefile -c --hidden-import $SCRIPT_DIRECTORY\version --hidden-import $SCRIPT_DIRECTORY\upgrade --hidden-import $SCRIPT_DIRECTORY\db --hidden-import $SCRIPT_DIRECTORY\utils --hidden-import $SCRIPT_DIRECTORY\config --hidden-import $SCRIPT_DIRECTORY\app --hidden-import $SCRIPT_DIRECTORY\backup --hidden-import $SCRIPT_DIRECTORY\pre_check --hidden-import $SCRIPT_DIRECTORY\w3b --hidden-import $SCRIPT_DIRECTORY\check --hidden-import $SCRIPT_DIRECTORY\UpdatePasswordPolicy --hidden-import $SCRIPT_DIRECTORY\XenvRunAtom --hidden-import $SCRIPT_DIRECTORY\win32timezone $SCRIPT_DIRECTORY\update.py

      - name: Commit and Tag version
        run: |
          git add ${{ github.workspace }}\$env:SUBDIRECTORY\$env:PROGRAM_VERSION_FILENAME
          git commit -m "Commit from GitHub Actions"
          git push origin master
          git tag -a "$new_build_version" -m "$new_build_version"
          git push origin refs/tags/$new_build_version

      - name: Publish Executable
        run: Copy-Item "${{ github.workspace }}\dist\update.exe" -Destination "$env:SHARED_DIRECTORY\update-$new_build_version.exe"
