name: TEST
  on:
  workflow_dispatch:
    inputs:
      IS_PRECONFIGURED:
        description: 'Is this a preconfigured build?'
        required: false
        default: 'true'
      BUILD_RELEASE:
        description: 'Release version if preconfigured'
        required: false
        default: '24.5.0'
      PACKAGE_NAME:
        description: 'Package name if preconfigured'
        required: false
        default: 'xstore-components-update-Ug31.0_Ug31.0_Ins31.0_x752_20241028-095120.jar'
  jobs:
  upgrade-jar-release:
